//* Useful extension
//* code --list-extensions > vscode-extensions.txt

// aaron-bond.better-comments
// anseki.vscode-color
// arturock.gitstash
// bierner.markdown-emoji
// bracketpaircolordlw.bracket-pair-color-dlw
// bradlc.vscode-tailwindcss
// britesnow.vscode-toggle-quotes
// chadalen.vscode-jetbrains-icon-theme
// christian-kohler.npm-intellisense
// christian-kohler.path-intellisense
// codestackr.codestackr-theme
// csstools.postcss
// ctf0.vscode-terminal-themes
// diemasmichiels.emulate
// diz.ecsstractor-port
// donjayamanne.githistory
// dotjoshjohnson.xml
// eamodio.gitlens
// ecmel.vscode-html-css
// esbenp.prettier-vscode
// formulahendry.auto-rename-tag
// fractalbrew.backticks
// github.github-vscode-theme
// github.remotehub
// github.vscode-github-actions
// graphql.vscode-graphql
// graphql.vscode-graphql-syntax
// helixquar.randomeverything
// htmllessonsru.simple-random-theme
// huizhou.githd
// iceworks-team.iceworks-style-helper
// imekachi.webstorm-darcula
// izcream.darkula
// k--kato.intellij-idea-keybindings
// kisstkondoros.vscode-gutter-preview
// lehoanganh298.json-lines-viewer
// lihui.vs-color-picker
// liviuschera.noctis
// mechatroner.rainbow-csv
// mgmcdermott.vscode-language-babel
// mhutchie.git-graph
// mongodb.mongodb-vscode
// mrmlnc.vscode-json5
// mrmlnc.vscode-scss
// ms-azuretools.vscode-docker
// ms-python.debugpy
// ms-python.python
// ms-python.vscode-pylance
// ms-vscode-remote.remote-containers
// ms-vscode-remote.remote-wsl
// ms-vscode.azure-repos
// ms-vscode.remote-repositories
// mtxr.sqltools
// naumovs.color-highlight
// nucllear.vscode-extension-auto-import
// pkief.material-icon-theme
// pmneo.tsimporter
// prisma.prisma
// redhat.vscode-yaml
// simonsiefke.svg-preview
// steoates.autoimport
// streetsidesoftware.code-spell-checker
// stringham.move-ts
// syler.sass-indented
// tabnine.tabnine-vscode
// techer.open-in-browser
// tombonnike.vscode-status-bar-format-toggle
// tonybaloney.vscode-pets
// unifiedjs.vscode-mdx
// visualstudioexptteam.intellicode-api-usage-examples
// visualstudioexptteam.vscodeintellicode
// voldemortensen.rainbow-tags
// vunguyentuan.vscode-postcss
// wix.vscode-import-cost
// wscats.eno
// xabikos.javascriptsnippets
// zainchen.json
